uniform vec4 u_perframe[20];
#define u_invViewProj0     u_perframe[0]
#define u_invViewProj1     u_perframe[1]
#define u_invViewProj2     u_perframe[2]
#define u_invViewProj3     u_perframe[3]
#define u_cameraMtx0       u_perframe[4]
#define u_cameraMtx1       u_perframe[5]
#define u_cameraMtx2       u_perframe[6]
#define u_cameraMtx3       u_perframe[7]
#define u_lightDir         u_perframe[8].xyz
#define u_width            u_perframe[8].w
#define u_lightCol         u_perframe[9].xyz
#define u_height           u_perframe[9].w
#define u_volumeMin        u_perframe[10].xyz
#define u_volumeSpacing    u_perframe[10].w
#define u_volumeMax        u_perframe[11].xyz
#define u_time             u_perframe[11].w
#define u_volumeSize       u_perframe[12].xyz
#define u_exposition       u_perframe[12].w
#define u_skyLuminance     u_perframe[13].xyz
#define u_sunBloom		   u_perframe[13].w
#define u_sunLuminance	   u_perframe[14].xyz
#define u_sunSize		   u_perframe[14].w
#define u_perezCoeff0	   u_perframe[15]
#define u_perezCoeff1	   u_perframe[16]
#define u_perezCoeff2	   u_perframe[17]
#define u_perezCoeff3	   u_perframe[18]
#define u_perezCoeff4	   u_perframe[19]

uniform vec4 u_perdraw[3];
#define u_texDiffuseFactor   u_perdraw[0].xyz
#define u_texRoughnessFactor u_perdraw[0].w
#define u_texNormalFactor    u_perdraw[1].xyz
#define u_texMetallicFactor  u_perdraw[1].w
#define u_probeGridPos       u_perdraw[2].xyz
#define u_unused20           u_perdraw[2].w

